# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d178dd90798d8261ad401657c75d8857e98cb418b4deb13681a24fca0edae59fdac5992a183ca8a059816ab346953ab6915322f865ad717b5e7caaa153a24f

test:
  secret_key_base: afc22efadfeb74416d48f2b57b1958560d2fffb88d7da8d922c073dd5a2b0a1076fc7c7fcabe73bf08df6fc2da6f11e4471ff0cad19ddb2b68b951ff3f80202a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
